# Generated by Django 4.2.20 on 2025-05-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_group_groupmessage_groupmembership_groupjoinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='required_permission',
        ),
    ]
