# Generated by Django 4.2.20 on 2025-05-02 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_post_description_alter_vote_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupjoinrequest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupjoinrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='livechatsession',
            name='participants',
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 8, 15, 19, 313980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupJoinRequest',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='LiveChatSession',
        ),
    ]
