# Generated by Django 4.2.20 on 2025-05-02 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_groupjoinrequest_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 10, 30, 34, 28547, tzinfo=datetime.timezone.utc)),
        ),
    ]
