# Generated by Django 4.2.20 on 2025-05-03 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_post_dislikes_alter_post_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 11, 56, 32, 770373, tzinfo=datetime.timezone.utc)),
        ),
    ]
