# Generated by Django 4.2.20 on 2025-05-03 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_vote_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 12, 48, 11, 777270, tzinfo=datetime.timezone.utc)),
        ),
    ]
